{
 "title": "WRAP100",
 "tags": [
  "WRAP100",
  "WiFI"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "JOB", "query": { "query": "label_values(job)" } },
   {
    "name": "WRAP",
    "query": {
     "query": "label_values(up{job=\"airmax\"}, id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Software",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ubntStaName{job=\"$job\",id=\"$WRAP\",ubntStaMac=~\"E.*\"}",
     "legendFormat": "{{ubntStaName}}"
    }
   ]
  },
  {
   "title": "SSID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ubntWlStatSsid{job=\"$job\",id=\"$WRAP\"}",
     "legendFormat": "{{ubntWlStatSsid}}"
    }
   ]
  },
  {
   "title": "Project number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\",id=\"$WRAP\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "UpTime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{job=\"airmax\",id=\"$WRAP\"} / 100"
    }
   ]
  },
  {
   "title": "Wireless Mode:",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ubntRadioMode{job=\"$job\",id=\"$WRAP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Security",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ubntWlStatSecurity{job=\"$job\",id=\"$WRAP\"}",
     "legendFormat": "{{ubntWlStatSecurity}}"
    }
   ]
  },
  {
   "title": "IP-address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ifPhysAddress{job=\"$job\",ifIndex=\"2\",id=\"$WRAP\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MAC-address WLAN0",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ifPhysAddress{job=\"$job\",ifIndex=\"4\",id=\"$WRAP\"}",
     "legendFormat": "{{ifPhysAddress}}"
    }
   ]
  },
  {
   "title": "MAC-address LAN0",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ifPhysAddress{job=\"$job\",ifIndex=\"2\",id=\"$WRAP\"}",
     "legendFormat": "{{ifPhysAddress}}"
    }
   ]
  },
  {
   "title": "Power state",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "up{job=\"$job\",id=\"$WRAP\"}",
     "legendFormat": "UP/DOWN "
    }
   ]
  },
  {
   "title": "Radio Distance",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ubntRadioDistance{job=\"$job\",id=\"$WRAP\"}",
     "legendFormat": "{{km}}"
    }
   ]
  },
  {
   "title": "Channel Width",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ubntWlStatChanWidth{job=\"$job\",id=\"$WRAP\"} * 1000000",
     "legendFormat": "Channel Width"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ubntRadioFreq{job=\"airmax\",id=\"$WRAP\"} * 1000000",
     "legendFormat": "Channel Width"
    }
   ]
  },
  {
   "title": "Client Connection Quality",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ubntStaCcq{job=\"$job\",id=\"$WRAP\",ubntStaMac=~\"E.*\"}",
     "legendFormat": "slot {{sysSlotIndex}}"
    }
   ]
  },
  {
   "title": "Total PDUs returned",
   "type": "stat",
   "description": "Total PDUs returned across all selected target jobs and target instances. Averaged over the selected time period in Grafana.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(snmp_scrape_pdus_returned{job=\"$job\",id=\"$WRAP\"})"
    }
   ]
  },
  {
   "title": "TX Power",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ubntRadioTxPower{job=\"$job\",id=\"$WRAP\"}",
     "legendFormat": "TX power"
    }
   ]
  },
  {
   "title": "Signal strength",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ubntWlStatSignal{job=\"$job\",id=\"$WRAP\"}",
     "legendFormat": "Signal strength"
    }
   ]
  },
  {
   "title": "RSSI signal",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-ubntRadioRssi{job=\"$job\",ubntRadioRssiIndex=\"1\",id=\"$WRAP\"}",
     "legendFormat": "RSSI signal(dBm)"
    }
   ]
  },
  {
   "title": "Noise floor",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ubntStaNoiseFloor{job=\"$job\",id=\"$WRAP\",ubntStaMac=~\"E.*\"}",
     "legendFormat": "Noise floor(dBm)"
    }
   ]
  },
  { "title": "States", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Destination states (WDS)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "ubntStaLastIp{job=\"$job\",id=\"$WRAP\",ubntStaMac=~\"E.*\"}"
    }
   ]
  },
  {
   "title": "CURRENT PORT SUMMARY",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ifOperStatus{job=\"$job\",id=\"$WRAP\"}"
    },
    {
     "expr": "irate(ifInOctets{job=\"airmax\",id=\"$WRAP\"}[$__rate_interval])*8"
    },
    {
     "expr": "irate(ifOutOctets{job=\"$job\",id=\"$WRAP\"}[$__rate_interval])*8"
    },
    {
     "expr": "ifInErrors{job=\"$job\",id=\"$WRAP\"}"
    },
    {
     "expr": "irate(ifInErrors{job=\"$job\",id=\"$WRAP\"}[$__rate_interval])*8"
    }
   ]
  },
  { "title": "Destination states (users)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Destination states (users)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "ubntStaLastIp{job=\"$job\",id=\"$WRAP\",ubntStaMac!~\"E.*\"}"
    }
   ]
  },
  { "title": "TTX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "TX Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "ubntRadioTxPower{job=\"$job\",id=\"$WRAP\"}",
     "legendFormat": "dBm"
    }
   ]
  },
  {
   "title": "Signal strength",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "ubntWlStatSignal{job=\"$job\",id=\"$WRAP\"}",
     "legendFormat": "Signal strength(dBm)"
    }
   ]
  },
  {
   "title": "RSSI signal",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "-ubntRadioRssi{job=\"$job\",ubntRadioRssiIndex=\"1\",id=\"$WRAP\"}",
     "legendFormat": "RSSI signal(dBm)"
    }
   ]
  },
  {
   "title": "Noise floor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "ubntStaNoiseFloor{job=\"$job\",id=\"$WRAP\"}",
     "legendFormat": "Noise floor(dBm)"
    }
   ]
  },
  {
   "title": "Scrape Duration by Job",
   "type": "timeseries",
   "description": "Sum of scrape durations for specific instance",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum by (instance) (snmp_scrape_duration_seconds{job=\"$job\",id=\"$WRAP\"})",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "Trafic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "trafic Ethernet",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ifInOctets{job=\"$job\",ifIndex=\"6\",id=\"$WRAP\"}[$__rate_interval])*8",
     "legendFormat": "IN"
    },
    {
     "expr": "-irate(ifOutOctets{job=\"$job\",ifIndex=\"6\",id=\"$WRAP\"}[$__rate_interval])*8",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "trafic WiFi",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ifInOctets{job=\"$job\",ifIndex=\"5\",id=\"$WRAP\"}[$__rate_interval])*8",
     "legendFormat": "IN"
    },
    {
     "expr": "-irate(ifOutOctets{job=\"$job\",ifIndex=\"5\",id=\"$WRAP\"}[$__rate_interval])*8",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "TX/RX",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ubntWlStatRxRate{job=\"$job\",id=\"$WRAP\"}[$__rate_interval])*8",
     "legendFormat": "RX"
    },
    {
     "expr": "-irate(ubntWlStatTxRate{job=\"$job\",id=\"$WRAP\"}[$__rate_interval])*8",
     "legendFormat": "TX"
    }
   ]
  }
 ]
}